language: java

dist: trusty
sudo: required
script: ./gradlew build --stacktrace

jdk:
  - oraclejdk8

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
