rp:
  amqp:
    host: localhost
    user: rabbitmq
    pass: rabbitmq
    apiuser: rabbitmq
    apipass: rabbitmq
  db:
    user: rpuser
    pass: rppass
    host: localhost
  plugins:
    rootDir: /Users/pavel_bortnik/ReportPortal5/data/storage/
  datasource:
    maximumPoolSize: 12
  binarystore:
#    path: /Users/pavel_bortnik/ReportPortal5/data/storage
    type: minio
    minio:
      endpoint: http://localhost:9000
      accessKey: minio
      secretKey: minio123