server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:api}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      loadBalanced: true

rp:
  uat:
    serviceUrl: http://uat:9999
  mongo:
    host: mongodb
    port: 27017
    dbName: reportportal
    user:
    password:

spring:
  redis:
    host: redis
    port: 6379
  cloud:
    consul:
      host: consul
      discovery:
        hostname: api
        prefer-ip-address: false
