spring:
  cloud:
    consul:
      discovery:
        hostname: docker.for.mac.localhost
      host: localhost
rp:
  mongo:
    host: localhost
  uat:
    serviceUrl: http://localhost:8080/uat
  analyzer:
    url: http://localhost:8080/analyzer
