on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      scripts_version:
        description: 'Gradle scripts version'
        required: true
      bom_version:
        description: 'Commons bom version'
        required: true
      migrations_version:
        description: 'Db migrations version'
        required: true

env:
  GH_USER_NAME: github.actor
  SCRIPTS_VERSION: ${{ github.event.inputs.scripts_version }}
  BOM_VERSION: ${{ github.event.inputs.bom_version }}
  MIGRATIONS_VERSION: ${{ github.event.inputs.migrations_version }}
  RELEASE_VERSION: ${{ github.event.inputs.version }}
  REPOSITORY_URL: 'https://maven.pkg.github.com/'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          name: 'reportportal.io'
          email: 'support@reportportal.io'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release with Gradle
        id: release
        run: |
          ./gradlew release -PreleaseMode -Pscripts.version=${{env.SCRIPTS_VERSION}} \
          -Pbom.version=${{env.BOM_VERSION}} -Pmigrations.version=${{env.MIGRATIONS_VERSION}} \
          -PgithubUserName=${{env.GH_USER_NAME}} -PgithubToken=${{secrets.GITHUB_TOKEN}} \
          -PpublishRepo=${{ env.REPOSITORY_URL }}${{ github.repository }} \
          -PgpgPassphrase=${{secrets.GPG_PASSPHRASE}} -PgpgPrivateKey="${{secrets.GPG_PRIVATE_KEY}}" \
          -Prelease.releaseVersion=${{env.RELEASE_VERSION}}
